const motivationalQuotes: string[] = [
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream bigger. Do bigger.",
    "Doubt kills more dreams than failure ever will.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
    "If you’re working on something that you really care about, you don’t have to be pushed. The vision pulls you. – Steve Jobs",
    "People who are crazy enough to think they can change the world, are the ones who do. – Rob Siltanen",
    "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
    "We may encounter many defeats but we must not be defeated. – Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. – Johann Wolfgang Von Goethe",
    "Whether you think you can or think you can’t, you’re right. – Henry Ford",
    "Security is mostly a superstition. Life is either a daring adventure or nothing. – Helen Keller",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Creativity is intelligence having fun. – Albert Einstein"
];

export default motivationalQuotes;